Added TypeScript to home-page
team-prstmw/HousesForSaleSearcherTS pull request #3
Opened 2022-04-04 09:35 UTC by PatrykJurczyk

File HomePage and ObjectToArray has some bugs with fatching houses.

2022-04-04 21:31 UTC, FilipHalon requested changes
@PatrykJurczyk, please change also the structure of the files that you worked on in the folders `pages` and `components` so that it resembles the structure you all chose.

2022-04-04 21:31 UTC, FilipHalon commented on package.json
> +    "prop-types": "15.8.1",
I think `prop-types` could be removed as we're using TS.

2022-04-04 21:31 UTC, FilipHalon commented on src/components/HeaderSection/Header/Header.tsx
> +  const [logged, setLogged] = useState<boolean | string>(false);
It would probably be easier to work with, if it stored only the boolean values. Your TS is sound - what I mean is that it could probably be easier to convert a string value to a boolean one right away whenever it happens so that `logged` is always a boolean but anyway this function is going to be changed once it's integrated with our back-end so no need to change it now.

2022-04-04 21:31 UTC, FilipHalon commented on src/contexts/LoginProvider.tsx
>  import PropTypes from 'prop-types';
`PropTypes` can be removed.

2022-04-04 21:31 UTC, FilipHalon commented on src/contexts/LoginProvider.tsx
> +const LoginProvider: React.FC<React.ReactNode> = ({ children }) => {
Just `LoginProvider: React.FC` (without `<React.ReactNode>`) seem to work well. You could consider also importing `FC` directly: `import { FC, useState } from 'react';` to keep imports more consistent.

2022-04-04 21:31 UTC, FilipHalon commented on src/models/house.d.ts
> +type HouseType = {
The name is a little misleading as `HouseType` doesn't store data about the type of a house. The way I see it, I'd say the data is more about basic info of a house.

2022-04-04 21:31 UTC, FilipHalon commented on src/pages/HomePage/ListOfHouses/ListOfHouses.tsx
> +const options: string[] = ['Payment (Low to High)', 'Payment (High to Low)', 'A-Z', 'Z-A'];
As all options are known beforehand it could also be made `const options = ['Payment (Low to High)', 'Payment (High to Low)', 'A-Z', 'Z-A'] as const;` to narrow types further.

2022-04-04 21:31 UTC, FilipHalon commented on src/pages/HomePage/ListOfHouses/ListOfHouses.tsx
> +            renderInput={(params) => <TextField {...params} />} // To nie wiem jak rozwiązać
Is there still a problem with this?

2022-04-04 21:31 UTC, FilipHalon commented on src/pages/HomePage/ListOfHouses/ListOfHouses.tsx
> +              {...label} // Nie wiem jak to rozwiązać.
And how about this?

2022-04-07 18:10 UTC, FilipHalon requested changes
Well done with adding changes :rocket:! Don't forget to change the file structure inside `components` and `pages`.

2022-04-07 18:10 UTC, FilipHalon commented on src/models/house.d.ts
> +type BasicHouseType = {
How about `BasicHouseData`?

2022-04-07 18:10 UTC, FilipHalon commented on src/pages/HomePage/ListOfHouses/ListOfHouses.tsx
> +        {sortedHouses.map((item: BasicHouseType, i: number) => (
Declaring the type for `i` isn't necessary.

2022-04-07 18:10 UTC, FilipHalon commented on src/pages/HomePage/ListOfHouses/ListOfHouses.tsx
> +function ListOfHouses({ houses }: { houses: BasicHouseType[] }) {
Is your VSCode recognising the type `BasicHouseType`? My seems to not know where it came from :thinking:.

2022-04-09 11:38 UTC, FilipHalon approved these changes

2022-04-10 11:33 UTC, mgoniszewska approved these changes
I suggest giving more love to Interfaces less to inline type checking :D

2022-04-10 11:33 UTC, mgoniszewska commented on src/components/HomePage/MapSide/MapSide.tsx
> +function MapHouses({ houses }): any {
Why `any`? Shouldn't it be something like `JSX.Element`?

2022-04-10 11:33 UTC, mgoniszewska commented on src/components/RegisterLoginModal/RegisterLoginModal.tsx
> +function RegisterLoginModal(): any {
Same as above.

2022-04-10 16:05 UTC, merged